### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by konsumer** [nathanhoad/SayWhat#7]
Hey, great progam, and godot lib. It's my favorite because it doesn't get in the way, and the editor is slick.

Would you consider documenting all the ops available in the language? I am having trouble piecing together the syntax. All the keywords and some examples would be very helpful (if you can provide one, I'll even PR for the other.)

It took me a while to setup the Godot scene for it, too, so I'd be happy to provide a simple example, so people can get started (and evaluate it) faster.

An example of an issue I am having is this:

<img width="642" alt="Screen Shot 2021-02-18 at 8 58 55 AM" src="https://user-images.githubusercontent.com/83857/108392414-8e042900-71c7-11eb-80b7-55a48093710e.png">

`if HasMetTom` is not highlighting or working (it puts it in the name) and I'm not exactly sure how to make choices work (for example how do I `do` something in a choice?) Also, the `do` at the end disappears when I save it.

I pieced together this syntax from the screenshot here:
![screen](https://img.itch.zone/aW1nLzM5NzY0NjgucG5n/original/M%2FhztG.png)

but `do` and `if` both seem to not work.

**Comment by konsumer** [comment]
I saw some notes in your devlog, and I might be able to piece together some basic syntax-docs based on that (would you like a PR?), but as I mentioned, both the version on itch.io and the version here (in master, with `npm start`) is not working with any of those commands for me, so there may be some other problem. Is there any part I can help with? I'm good with js/react, but new to godot, so I could probly help a lot, with the editor part.

**Comment by nathanhoad** [comment]
I've been meaning to write proper docs so a PR would be fantastic.

Are you getting an error when running it locally with `npm start` or is it just not opening?

**Comment by konsumer** [comment]
well, kind of both.

At first it wouldn't open (white screen) but I had the prebuilt version open at the same time. I closed that, and it opened and worked fine, with no errors, but also `if` and `do` don't seem to work.

**Comment by nathanhoad** [comment]
From your screenshot it looks like you just need to wrap them in `[` and `]`.

```
[if !hasMetTom] Tom: Hello, my name is Tom.
```

and 

```
[do hasMetTom=true]
```

**Comment by konsumer** [comment]
Oh, duh, user-error. sorry. I needed brackets for commands. I will add that to my docs PR. I only realized after a fresh install, when I looked closer at the demo dialog. I discovered this while I was making a video (still pending upload as of now)
https://www.youtube.com/watch?v=Pva1K_ZKhBs

A linter, or at the very least syntax-highlighter would have helped. Would you be interested in a PR for that too? It would be cool if I could edit in my favorite editor (using a textmate-format language-definition, which will work for codemirror (web), vscode, atom, sublime, and many more) and add my own CLI-based build-commands for linting and exporting to the different formats. I don't have any experience writing a language grammar, but I'm happy to give it a go, and I think the code for turning it into other formats is all here. Maybe we could make a central `saywhat-node` repo for the actual "take this saywhat file and turn it into other formats", which includes a minimal CLI, and a `saywhat-grammar` that tracks support for editors.

I'm happy to help with all of these.

**Comment by konsumer** [comment]
Ok, I libraryized it, and made a CLI tool for it [here](https://github.com/notnullgames/saywhat-node).

I added you as project admin, but I am happy to move it somewhere, if you don;t want me as a maintainer, or want to keep it in a different org.

I leave publishing to you, unless you want it under my name: `npm version patch && npm publish`

After that, you can use it from npm, to cut down on code-duplication (I included your typescript def, `renderer/lib/util.ts:keyBy`, and main/export.ts) so it could be reused by importing that lib instead.

Next I'm going to finish up the usage docs and PR.

**Comment by konsumer** [comment]
I still need a compiler for the raw dialogue into a project file, and I'd like to make a linter.

**Comment by nathanhoad** [comment]
I'll move it under my account (to keep it all together) when you're ready but then add you as a maintainer.

**Comment by konsumer** [comment]
I think it's ready now, I just added compile to CLI/lib. We can save `lint` until I have a bit mroe time, as it's not somethign I already know about.

**Comment by konsumer** [comment]
I also added lint/pretty-print. My method may be a bit naive (regex-based) but I think it works ok, at least for now. The lint function returns an array of errors, so it could be used in the editor, if you want.

**Comment by konsumer** [comment]
I started work on a [demo project](https://github.com/notnullgames/saywhat-demo), but am having issues with getting the dialog to actually work, probably due to my lack of experience with godot. I just got started, so no scroll-management, or choice-menu or anything. It's not removing the old instances with `queue_free()`.Do you have example-code anywhere that uses saywhat?

**Comment by nathanhoad** [comment]
I can probably throw a quick Godot project together to give a rough example.

**Comment by nathanhoad** [comment]
Here's a quick example: https://github.com/nathanhoad/saywhat_godot_example

**Comment by konsumer** [comment]
This is perfect and simpler than what I was doing. Maybe just a.link to that in usage, and this issue seems resolved to me. Thanks!
